
/**
 *
 * @author Alan Soares
 */
public class CadastroVeiculos extends javax.swing.JFrame {

    /**
     * Creates new form CadastroVeiculos
     */
    public CadastroVeiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextoVeiculos = new javax.swing.JTextField();
        Cor = new javax.swing.JLabel();
        TextoCor = new javax.swing.JTextField();
        Placa = new javax.swing.JLabel();
        TextoPlaca = new javax.swing.JTextField();
        BtnSalvar = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Veículos");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Modelo do Veículo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 70, 120, 14);

        TextoVeiculos.setToolTipText("Dogote aqui o modelo do veículo.");
        getContentPane().add(TextoVeiculos);
        TextoVeiculos.setBounds(50, 90, 330, 22);

        Cor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Cor.setText("Cor do Veículo:");
        getContentPane().add(Cor);
        Cor.setBounds(50, 130, 100, 14);

        TextoCor.setToolTipText("Digite aqui a cor do veículo.");
        getContentPane().add(TextoCor);
        TextoCor.setBounds(50, 150, 230, 22);

        Placa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Placa.setText("Placa do Veículo:");
        getContentPane().add(Placa);
        Placa.setBounds(50, 190, 100, 14);

        TextoPlaca.setToolTipText("Digite aqui a placa do veículo.");
        getContentPane().add(TextoPlaca);
        TextoPlaca.setBounds(50, 210, 230, 22);

        BtnSalvar.setBackground(new java.awt.Color(51, 51, 255));
        BtnSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalvar.setText("Salvar");
        BtnSalvar.setToolTipText("Clique aqui para salvar os dados.");
        getContentPane().add(BtnSalvar);
        BtnSalvar.setBounds(100, 300, 72, 21);

        BtnVoltar.setBackground(new java.awt.Color(51, 51, 255));
        BtnVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        BtnVoltar.setText("Voltar");
        BtnVoltar.setToolTipText("Voltar para o menu");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVoltar);
        BtnVoltar.setBounds(220, 300, 72, 21);

        Fundo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastro de Veículos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(30, 30, 360, 360);

        setSize(new java.awt.Dimension(423, 455));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        TelaMenuCadastro telaMenu = new TelaMenuCadastro();
        telaMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel Cor;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Placa;
    private javax.swing.JTextField TextoCor;
    private javax.swing.JTextField TextoPlaca;
    private javax.swing.JTextField TextoVeiculos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
