
/**
 *
 * @author Alan Soares
 */
public class CadastroOficina extends javax.swing.JFrame {

    /**
     * Creates new form CadastroOficina
     */
    public CadastroOficina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatEntrada = new javax.swing.JLabel();
        DatSaida = new javax.swing.JLabel();
        TextDatSaida = new javax.swing.JFormattedTextField();
        Placa = new javax.swing.JLabel();
        TextPlaca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Serviço = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BtnSalvar = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        TextDatEntrada = new javax.swing.JFormattedTextField();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Oficina");
        setResizable(false);
        getContentPane().setLayout(null);

        DatEntrada.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DatEntrada.setText("Data da Entrada:");
        getContentPane().add(DatEntrada);
        DatEntrada.setBounds(40, 60, 100, 14);

        DatSaida.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DatSaida.setText("Data da Saída:");
        getContentPane().add(DatSaida);
        DatSaida.setBounds(240, 60, 90, 14);

        try {
            TextDatSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextDatSaida.setToolTipText("Digite a data de saída do veículo.");
        getContentPane().add(TextDatSaida);
        TextDatSaida.setBounds(240, 80, 80, 22);

        Placa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Placa.setText("Placa do Veículo:");
        getContentPane().add(Placa);
        Placa.setBounds(40, 120, 110, 14);

        TextPlaca.setToolTipText("Digite aqui a placa do veículo.");
        getContentPane().add(TextPlaca);
        TextPlaca.setBounds(40, 140, 120, 22);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Serviço Realizado:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 180, 110, 14);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("Digite aqui o serviço realizado.");
        Serviço.setViewportView(jTextArea1);

        getContentPane().add(Serviço);
        Serviço.setBounds(40, 200, 340, 150);

        BtnSalvar.setBackground(new java.awt.Color(51, 51, 255));
        BtnSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalvar.setText("Salvar");
        BtnSalvar.setToolTipText("Clique aqui para salvar os dados.");
        getContentPane().add(BtnSalvar);
        BtnSalvar.setBounds(90, 370, 72, 21);

        BtnVoltar.setBackground(new java.awt.Color(51, 51, 255));
        BtnVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        BtnVoltar.setText("Voltar");
        BtnVoltar.setToolTipText("Voltar para o menu");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVoltar);
        BtnVoltar.setBounds(210, 370, 72, 21);

        try {
            TextDatEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(TextDatEntrada);
        TextDatEntrada.setBounds(40, 80, 100, 22);

        Fundo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastro Veículos Oficina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(20, 20, 380, 420);

        setSize(new java.awt.Dimension(427, 487));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        TelaMenuCadastro telaMenu = new TelaMenuCadastro();
        telaMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroOficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroOficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroOficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroOficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroOficina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel DatEntrada;
    private javax.swing.JLabel DatSaida;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Placa;
    private javax.swing.JScrollPane Serviço;
    private javax.swing.JFormattedTextField TextDatEntrada;
    private javax.swing.JFormattedTextField TextDatSaida;
    private javax.swing.JTextField TextPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
