
/**
 *
 * @author Alan Soares
 */
public class CadastroAtividades extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAtividades
     */
    public CadastroAtividades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Motorista = new javax.swing.JLabel();
        TextoNome = new javax.swing.JTextField();
        Placa = new javax.swing.JLabel();
        TextoPlaca = new javax.swing.JTextField();
        Destin = new javax.swing.JLabel();
        TextoDestino = new javax.swing.JTextField();
        DataSaida = new javax.swing.JLabel();
        DataChegada = new javax.swing.JLabel();
        KMSaida = new javax.swing.JLabel();
        TextoKmSaida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TextoKmChegada = new javax.swing.JTextField();
        BtnSalvar = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        DataHoraSaida = new javax.swing.JFormattedTextField();
        DataHoraChegada = new javax.swing.JFormattedTextField();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atividades");
        setResizable(false);
        getContentPane().setLayout(null);

        Motorista.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Motorista.setText("Nome do Motorista:");
        getContentPane().add(Motorista);
        Motorista.setBounds(40, 70, 120, 14);

        TextoNome.setToolTipText("Digite o nome do motorista.");
        getContentPane().add(TextoNome);
        TextoNome.setBounds(40, 90, 390, 22);

        Placa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Placa.setText("Placa do Veículo:");
        getContentPane().add(Placa);
        Placa.setBounds(40, 130, 100, 14);

        TextoPlaca.setToolTipText("Digite a placa do veículo.");
        getContentPane().add(TextoPlaca);
        TextoPlaca.setBounds(40, 150, 140, 22);

        Destin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Destin.setText("Destino:");
        getContentPane().add(Destin);
        Destin.setBounds(270, 130, 50, 14);

        TextoDestino.setToolTipText("Digite o destino.");
        getContentPane().add(TextoDestino);
        TextoDestino.setBounds(270, 150, 160, 22);

        DataSaida.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DataSaida.setText("Data e Hora da Saída:");
        getContentPane().add(DataSaida);
        DataSaida.setBounds(40, 190, 130, 16);

        DataChegada.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DataChegada.setText("Data e Hora da Chegada:");
        getContentPane().add(DataChegada);
        DataChegada.setBounds(270, 190, 160, 14);

        KMSaida.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        KMSaida.setText("Km Saída:");
        getContentPane().add(KMSaida);
        KMSaida.setBounds(40, 250, 60, 16);

        TextoKmSaida.setToolTipText("Digite o Km da saída.");
        getContentPane().add(TextoKmSaida);
        TextoKmSaida.setBounds(40, 270, 140, 22);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Km Chegada:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 250, 90, 14);

        TextoKmChegada.setToolTipText("Digite o KM da chegada.");
        getContentPane().add(TextoKmChegada);
        TextoKmChegada.setBounds(270, 270, 160, 22);

        BtnSalvar.setBackground(new java.awt.Color(51, 51, 255));
        BtnSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalvar.setText("Salvar");
        BtnSalvar.setToolTipText("Clique aqui para salvar os dados.");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalvar);
        BtnSalvar.setBounds(120, 340, 72, 21);

        BtnVoltar.setBackground(new java.awt.Color(51, 51, 255));
        BtnVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        BtnVoltar.setText("Voltar");
        BtnVoltar.setToolTipText("Voltar para o menu");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVoltar);
        BtnVoltar.setBounds(250, 340, 72, 21);

        try {
            DataHoraSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### - ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(DataHoraSaida);
        DataHoraSaida.setBounds(40, 210, 78, 22);

        try {
            DataHoraChegada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### - ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DataHoraChegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataHoraChegadaActionPerformed(evt);
            }
        });
        getContentPane().add(DataHoraChegada);
        DataHoraChegada.setBounds(270, 210, 78, 22);

        Fundo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastro das Atividades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(30, 20, 420, 390);

        setSize(new java.awt.Dimension(484, 463));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        TelaMenuCadastro telaMenu = new TelaMenuCadastro();
        telaMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void DataHoraChegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataHoraChegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataHoraChegadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAtividades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel DataChegada;
    private javax.swing.JFormattedTextField DataHoraChegada;
    private javax.swing.JFormattedTextField DataHoraSaida;
    private javax.swing.JLabel DataSaida;
    private javax.swing.JLabel Destin;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel KMSaida;
    private javax.swing.JLabel Motorista;
    private javax.swing.JLabel Placa;
    private javax.swing.JTextField TextoDestino;
    private javax.swing.JTextField TextoKmChegada;
    private javax.swing.JTextField TextoKmSaida;
    private javax.swing.JTextField TextoNome;
    private javax.swing.JTextField TextoPlaca;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
