
/**
 *
 * @author Alan Soares
 */
public class CadastroMultas extends javax.swing.JFrame {

    /**
     * Creates new form CadastroMultas
     */
    public CadastroMultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MotoristaInfra = new javax.swing.JLabel();
        TextoMotorInfra = new javax.swing.JTextField();
        Data = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        TextHora = new javax.swing.JFormattedTextField();
        Local = new javax.swing.JLabel();
        TextoLocal = new javax.swing.JTextField();
        BtnSalvar = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        TextoData = new javax.swing.JFormattedTextField();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Multas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        MotoristaInfra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MotoristaInfra.setText("Motorista Infrator:");
        getContentPane().add(MotoristaInfra);
        MotoristaInfra.setBounds(40, 70, 110, 14);

        TextoMotorInfra.setToolTipText("Digite o nome do motorista infrator.");
        getContentPane().add(TextoMotorInfra);
        TextoMotorInfra.setBounds(40, 90, 320, 22);

        Data.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Data.setText("Data da Infração:");
        getContentPane().add(Data);
        Data.setBounds(40, 130, 100, 16);

        Hora.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Hora.setText("Hora da Infração:");
        getContentPane().add(Hora);
        Hora.setBounds(230, 130, 110, 14);

        try {
            TextHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextHora.setToolTipText("Digite a hora da infração.");
        getContentPane().add(TextHora);
        TextHora.setBounds(230, 150, 100, 22);

        Local.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Local.setText("Local da Infração:");
        getContentPane().add(Local);
        Local.setBounds(40, 190, 110, 16);

        TextoLocal.setToolTipText("Digite o local da infração.");
        TextoLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoLocalActionPerformed(evt);
            }
        });
        getContentPane().add(TextoLocal);
        TextoLocal.setBounds(40, 210, 320, 22);

        BtnSalvar.setBackground(new java.awt.Color(51, 51, 255));
        BtnSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalvar.setText("Salvar");
        BtnSalvar.setToolTipText("Clique aqui para salvar os dados.");
        getContentPane().add(BtnSalvar);
        BtnSalvar.setBounds(90, 340, 72, 21);

        BtnVoltar.setBackground(new java.awt.Color(0, 51, 255));
        BtnVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        BtnVoltar.setText("Voltar");
        BtnVoltar.setToolTipText("Voltar para o menu");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVoltar);
        BtnVoltar.setBounds(210, 340, 75, 21);

        try {
            TextoData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(TextoData);
        TextoData.setBounds(40, 150, 100, 22);

        Fundo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastro Multas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(20, 30, 360, 360);

        setSize(new java.awt.Dimension(408, 442));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextoLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoLocalActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        TelaMenuCadastro telaMenu = new TelaMenuCadastro();
        telaMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel Data;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Local;
    private javax.swing.JLabel MotoristaInfra;
    private javax.swing.JFormattedTextField TextHora;
    private javax.swing.JFormattedTextField TextoData;
    private javax.swing.JTextField TextoLocal;
    private javax.swing.JTextField TextoMotorInfra;
    // End of variables declaration//GEN-END:variables
}
