/**
 *
 * @author Alan Soares
 */
public class CadastroMotorista extends javax.swing.JFrame {

    /**
     * Creates new form CadastroMotorista
     */
    public CadastroMotorista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();
        titcpf = new javax.swing.JLabel();
        CNH = new javax.swing.JLabel();
        TextoCNH = new javax.swing.JTextField();
        Categoria = new javax.swing.JLabel();
        ComboBoxCategoria = new javax.swing.JComboBox<>();
        BtnSalvar = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        TextoCPF = new javax.swing.JFormattedTextField();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Motoristas");
        setResizable(false);
        getContentPane().setLayout(null);

        Nome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Nome.setText("Nome Completo:");
        getContentPane().add(Nome);
        Nome.setBounds(50, 70, 100, 14);

        TextNome.setToolTipText("Digite o nome do motorista.");
        getContentPane().add(TextNome);
        TextNome.setBounds(50, 100, 270, 22);

        titcpf.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        titcpf.setText("CPF:");
        getContentPane().add(titcpf);
        titcpf.setBounds(50, 130, 40, 14);

        CNH.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CNH.setText("Número CNH:");
        getContentPane().add(CNH);
        CNH.setBounds(50, 190, 100, 16);

        TextoCNH.setToolTipText("Digite o número da CNH.");
        getContentPane().add(TextoCNH);
        TextoCNH.setBounds(50, 210, 270, 22);

        Categoria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Categoria.setText("Categoria CNH:");
        getContentPane().add(Categoria);
        Categoria.setBounds(50, 240, 90, 20);

        ComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "A", "B", "D", "E", "AB", "AD", "AE" }));
        ComboBoxCategoria.setToolTipText("Escolha a categoria da CNH.");
        getContentPane().add(ComboBoxCategoria);
        ComboBoxCategoria.setBounds(50, 260, 90, 22);

        BtnSalvar.setBackground(new java.awt.Color(51, 51, 255));
        BtnSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalvar.setText("Salvar");
        BtnSalvar.setToolTipText("Clique aqui para salvar os dados.");
        getContentPane().add(BtnSalvar);
        BtnSalvar.setBounds(90, 310, 72, 21);

        BtnVoltar.setBackground(new java.awt.Color(51, 51, 255));
        BtnVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        BtnVoltar.setText("Voltar");
        BtnVoltar.setToolTipText("Voltar para o menu");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVoltar);
        BtnVoltar.setBounds(200, 310, 72, 21);

        try {
            TextoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(TextoCPF);
        TextoCPF.setBounds(50, 150, 270, 22);

        Fundo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastro Motoristas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(23, 6, 320, 360);

        setSize(new java.awt.Dimension(367, 431));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        TelaMenuCadastro telaMenu = new TelaMenuCadastro();
        telaMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMotorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel CNH;
    private javax.swing.JLabel Categoria;
    private javax.swing.JComboBox<String> ComboBoxCategoria;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField TextNome;
    private javax.swing.JTextField TextoCNH;
    private javax.swing.JFormattedTextField TextoCPF;
    private javax.swing.JLabel titcpf;
    // End of variables declaration//GEN-END:variables
}
