
import javax.swing.JOptionPane;

/**
 *
 * @author Alan Soares
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloEmpresa = new javax.swing.JLabel();
        Empresa = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();
        TituloLogin = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        EscSenha = new javax.swing.JLabel();
        BtnEntrar = new javax.swing.JButton();
        UserSenha = new javax.swing.JPasswordField();
        Login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        TituloEmpresa.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        TituloEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        TituloEmpresa.setText("LogisticsCompany");
        TituloEmpresa.setToolTipText("Nome da Empresa");
        getContentPane().add(TituloEmpresa);
        TituloEmpresa.setBounds(20, 150, 132, 17);

        Empresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo2.png"))); // NOI18N
        getContentPane().add(Empresa);
        Empresa.setBounds(10, 70, 160, 330);

        Fundo.setBackground(new java.awt.Color(255, 255, 255));
        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo azul.jpg"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 170, 420);

        TituloLogin.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        TituloLogin.setText("Bem Vindo!");
        getContentPane().add(TituloLogin);
        TituloLogin.setBounds(230, 60, 210, 42);

        UserName.setBackground(new java.awt.Color(242, 242, 242));
        UserName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        UserName.setToolTipText("Digite seu usuário");
        UserName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });
        getContentPane().add(UserName);
        UserName.setBounds(200, 160, 280, 40);

        EscSenha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        EscSenha.setText("Esqueceu a senha? Clique aqui.");
        EscSenha.setToolTipText("Clique aqui se esqueceu a senha.");
        EscSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EscSenhaMouseClicked(evt);
            }
        });
        getContentPane().add(EscSenha);
        EscSenha.setBounds(250, 340, 190, 14);

        BtnEntrar.setBackground(new java.awt.Color(51, 51, 255));
        BtnEntrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEntrar.setText("Entrar");
        BtnEntrar.setToolTipText("Clique aqui para entrar!");
        BtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEntrar);
        BtnEntrar.setBounds(300, 290, 72, 21);

        UserSenha.setBackground(new java.awt.Color(242, 242, 242));
        UserSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, null), "Senha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        UserSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(UserSenha);
        UserSenha.setBounds(200, 230, 280, 40);

        Login.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Login.setText("Realize seu login para acessar o programa.");
        getContentPane().add(Login);
        Login.setBounds(210, 120, 260, 14);

        setSize(new java.awt.Dimension(511, 431));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
        String usuario = UserName.getText();
        String senha = UserSenha.getText();

        if (usuario.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos");
        } else {

            boolean loginValido = verificarLogin(usuario, senha);

            if (loginValido) {

                TelaMenuCadastro menuCadastro = new TelaMenuCadastro();
                menuCadastro.setVisible(true);

                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos");
            }
        }


    }//GEN-LAST:event_BtnEntrarActionPerformed

    private void EscSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscSenhaMouseClicked
        JOptionPane.showMessageDialog(null, "Por favor entre em contato com suporte para recuperar sua senha.");

    }//GEN-LAST:event_EscSenhaMouseClicked

    private void UserSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEntrar;
    private javax.swing.JLabel Empresa;
    private javax.swing.JLabel EscSenha;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel TituloEmpresa;
    private javax.swing.JLabel TituloLogin;
    private javax.swing.JTextField UserName;
    private javax.swing.JPasswordField UserSenha;
    // End of variables declaration//GEN-END:variables

    private boolean verificarLogin(String usuario, String senha) {
        // Retorne true se o login for válido, caso contrário, retorne false
        return usuario.equals("admin") && senha.equals("123");
    }
}
