
/**
 *
 * @author Alan Soares
 */
public class TelaMenuCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenuCadastro
     */
    public TelaMenuCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCadMot = new javax.swing.JButton();
        motorista = new javax.swing.JLabel();
        BtnCadVei = new javax.swing.JButton();
        Veiculos = new javax.swing.JLabel();
        BtnCadMultas = new javax.swing.JButton();
        Multas = new javax.swing.JLabel();
        BtnCadTarefas = new javax.swing.JButton();
        Tarefas = new javax.swing.JLabel();
        BtnCadOficina = new javax.swing.JButton();
        Oficina = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setResizable(false);
        getContentPane().setLayout(null);

        BtnCadMot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/motorista150.png"))); // NOI18N
        BtnCadMot.setToolTipText("Clique aqui para cadastar Motorista.");
        BtnCadMot.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnCadMot.setMaximumSize(new java.awt.Dimension(204, 204));
        BtnCadMot.setMinimumSize(new java.awt.Dimension(204, 204));
        BtnCadMot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadMotActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCadMot);
        BtnCadMot.setBounds(60, 70, 100, 100);

        motorista.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        motorista.setText("Cadastrar Motorista");
        getContentPane().add(motorista);
        motorista.setBounds(60, 180, 120, 14);

        BtnCadVei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/camihao200.jpg"))); // NOI18N
        BtnCadVei.setToolTipText("Clique aqui para cadastar veículos.");
        BtnCadVei.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnCadVei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadVeiActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCadVei);
        BtnCadVei.setBounds(250, 70, 100, 100);

        Veiculos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Veiculos.setText("Cadastrar Veículos");
        getContentPane().add(Veiculos);
        Veiculos.setBounds(240, 180, 110, 14);

        BtnCadMultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/multa200.jpg"))); // NOI18N
        BtnCadMultas.setToolTipText("Clique aqui para cadastar Multas.");
        BtnCadMultas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnCadMultas.setMaximumSize(new java.awt.Dimension(204, 204));
        BtnCadMultas.setMinimumSize(new java.awt.Dimension(204, 204));
        BtnCadMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadMultasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCadMultas);
        BtnCadMultas.setBounds(420, 70, 100, 100);

        Multas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Multas.setText("Cadastrar Multas");
        getContentPane().add(Multas);
        Multas.setBounds(420, 180, 100, 16);

        BtnCadTarefas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/tarefas200.jpg"))); // NOI18N
        BtnCadTarefas.setToolTipText("Clique aqui para cadastar Atividades.");
        BtnCadTarefas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnCadTarefas.setMaximumSize(new java.awt.Dimension(204, 204));
        BtnCadTarefas.setMinimumSize(new java.awt.Dimension(204, 204));
        BtnCadTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadTarefasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCadTarefas);
        BtnCadTarefas.setBounds(150, 230, 110, 110);

        Tarefas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Tarefas.setText("Cadastrar Atividades");
        getContentPane().add(Tarefas);
        Tarefas.setBounds(150, 350, 120, 14);

        BtnCadOficina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/oficina3.jpeg"))); // NOI18N
        BtnCadOficina.setToolTipText("Clique aqui para cadastar veículos na oficina.");
        BtnCadOficina.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnCadOficina.setMaximumSize(new java.awt.Dimension(204, 204));
        BtnCadOficina.setMinimumSize(new java.awt.Dimension(204, 204));
        BtnCadOficina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadOficinaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCadOficina);
        BtnCadOficina.setBounds(340, 230, 110, 110);

        Oficina.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Oficina.setText("Oficina");
        getContentPane().add(Oficina);
        Oficina.setBounds(380, 350, 50, 16);

        Fundo.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        Fundo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Menu de Cadastros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(30, 20, 540, 400);

        Menu.setText("Menu");

        Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Menu.add(Sair);

        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(604, 472));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCadMotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadMotActionPerformed
        CadastroMotorista cadastroMotorista = new CadastroMotorista();
        cadastroMotorista.setVisible(true);
        setVisible(false);


    }//GEN-LAST:event_BtnCadMotActionPerformed

    private void BtnCadVeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadVeiActionPerformed
        CadastroVeiculos Cadastro = new CadastroVeiculos();
        Cadastro.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BtnCadVeiActionPerformed

    private void BtnCadMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadMultasActionPerformed
        CadastroMultas Cadastro = new CadastroMultas();
        Cadastro.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BtnCadMultasActionPerformed

    private void BtnCadTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadTarefasActionPerformed
        CadastroAtividades Cadastro = new CadastroAtividades();
        Cadastro.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BtnCadTarefasActionPerformed

    private void BtnCadOficinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadOficinaActionPerformed
        CadastroOficina Cadastro = new CadastroOficina();
        Cadastro.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BtnCadOficinaActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadMot;
    private javax.swing.JButton BtnCadMultas;
    private javax.swing.JButton BtnCadOficina;
    private javax.swing.JButton BtnCadTarefas;
    private javax.swing.JButton BtnCadVei;
    private javax.swing.JLabel Fundo;
    private javax.swing.JMenu Menu;
    private javax.swing.JLabel Multas;
    private javax.swing.JLabel Oficina;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JLabel Tarefas;
    private javax.swing.JLabel Veiculos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel motorista;
    // End of variables declaration//GEN-END:variables
}
